# Generated by Django 6.0 on 2025-12-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('character_class', models.CharField(choices=[('artificer', 'Artificer'), ('barbarian', 'Barbarian'), ('bard', 'Bard'), ('cleric', 'Cleric'), ('druid', 'Druid'), ('fighter', 'Fighter'), ('monk', 'Monk'), ('paladin', 'Paladin'), ('ranger', 'Ranger'), ('rogue', 'Rogue'), ('sorcerer', 'Sorcerer'), ('warlock', 'Warlock'), ('wizard', 'Wizard')], max_length=30)),
                ('character_race', models.CharField(choices=[('dragonborn', 'Dragonborn'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('gnome', 'Gnome'), ('half-elf', 'Half-Elf'), ('half-orc', 'Half-Orc'), ('human', 'Human'), ('orc', 'Orc'), ('tiefling', 'Tiefling')], max_length=30)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
            ],
        ),
    ]
